name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  id-token: write

jobs:
  publish-jsr:
    name: Publish to JSR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1

      - run: deno publish
